Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreOakberry.Business.Services;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IAboutUsService _aboutUs;

        public AboutUsController(AppDbContext context, IAboutUsService aboutUs)
        {
            _context = context;
            _aboutUs = aboutUs;
        }

        public IActionResult Index()
        {
            var aboutUsImage = _context.AboutUsses.Select(e => e.ImageUrlLeft).FirstOrDefault();
            ViewBag.AboutUsImage = aboutUsImage;
            return View();
        }
    }
}

Controllers/AgentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Controllers
{
    public class AgentsController : Controller
    {
        private readonly AppDbContext _context;

        public AgentsController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var agents = _context.Agents
                .Include(e => e.Properties)
                .Take(8)
                .ToList();
            ViewBag.BgImage = _context.BgImages.Where(e => e.Id == 1).Select(e => e.BackgroundImage).FirstOrDefault();
            return View(agents);
        }
    }
}

Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Controllers
{
    public class BlogController : Controller
    {
        private readonly AppDbContext _context;

        public BlogController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var blogs = _context.Blogs
                .Include(e => e.Comments)
                .Include(e => e.Tags)
                .ToList();
            ViewBag.BgImage = _context.BgImages.Where(e => e.Id == 2).Select(e => e.BackgroundImage).FirstOrDefault();
            return View(blogs);
        }

        public async Task<IActionResult> Detail(int id)
        {
            var blog = await _context.Blogs
                .Include(e => e.Comments)
                .ThenInclude(e => e.Replies)
                .Include(e => e.Tags)
                .FirstOrDefaultAsync(e => e.Id == id);

            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

    }
}

Controllers/PropertyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Controllers
{
    public class PropertyController : Controller
    {
        private readonly AppDbContext _context;

        public PropertyController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var properties = _context.Properties
                .Include(e => e.PropertyImages)
                .Include(b => b.PropertyCategory)
                .Include(a => a.Agent)
                .Take(8)
                .ToList();
            return View(properties);
        }

        public IActionResult Search(string propertyName, int propertyType, string location, int priceLimit)
        {
            // Tüm mülkleri çek
            var properties = _context.Properties
                .Include(e => e.PropertyImages)
                .Include(b => b.PropertyCategory)
                .Include(a => a.Agent)
                .ToList();

            // propertyName değeri varsa, isme göre filtrele
            if (!string.IsNullOrEmpty(propertyName))
            {
                properties = properties.Where(p => p.Name.Contains(propertyName, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            // propertyType değeri 0 ise tüm özellikleri listele
            if (propertyType == 0)
            {
                properties = properties.ToList();
            }
            // propertyType değeri varsa, kategoriye göre filtrele
            else if (propertyType > 0)
            {
                properties = properties.Where(p => p.CategoryId == propertyType).ToList();
            }

            // location değeri varsa, şehire göre filtrele
            if (!string.IsNullOrEmpty(location))
            {
                properties = properties.Where(p => p.Address.Contains(location, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            // priceLimit değeri varsa, fiyat sınırlarına göre filtrele
            if (priceLimit != 100)
            {
                properties = properties.Where(p => p.Price <= priceLimit).OrderBy(a => a.Price).ToList();
            }

            // Eğer hiç veri bulunamazsa, kullanıcıya bir hata mesajı göster
            if (properties.Count == 0)
            {
                ViewBag.ErrorMessage = "Arama kriterlerinize uygun mülk bulunamadı.";
            }

            return View("Search", properties);
        }
    }
}

Views/Shared/Components/AboutUs/AboutUsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Models;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Views.Shared.Components.AboutUs
{
    public class AboutUsViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public AboutUsViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var aboutUsData = await _context.AboutUsses.FirstOrDefaultAsync();

            var viewModel = new AboutUsStatisticViewModel
            {
                TotalProperties = _context.Properties.Count(),
                QualifiedRealtors = _context.Agents.Count(),
                AboutUsData = aboutUsData
            };

            return View(viewModel);
        }
    }
}

Views/Shared/Components/Agents/AgentsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Views.Shared.Components.Agents
{
    public class AgentsViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public AgentsViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var agents = _context.Agents
                .Take(4)
                .Include(a => a.Properties)
                .ToList();
            return View(agents);
        }
    }
}

Views/Shared/Components/Blog/BlogViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.EntityFramework;

namespace NetCoreOakberry.Views.Shared.Components.Blog
{
    public class BlogViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public BlogViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var blogs = _context.Blogs
                .Take(4)
                .Include(e => e.Comments)
                .ToList();
            return View(blogs);
        }
    }
}

Views/Shared/Components/CategoriesPlaces/CategoriesPlacesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreOakberry.Persistence;

using NetCoreOakberry.Persistence.Entities;

namespace NetCoreOakberry.Views.Shared.Components.CategoriesPlaces
{
    public class CategoriesPlacesViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public CategoriesPlacesViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cityStatistics = _context.Properties
                .GroupBy(p => p.City)
                .Select(group => new CityStatistic
                {
                    City = group.Key,
                    PropertyCount = group.Count()
                })
                .OrderByDescending(stat => stat.PropertyCount)
                .Take(12)
                .ToList();

            return View(cityStatistics);
        }
    }
}

Views/Shared/Components/FeaturedProperty/FeaturedPropertyViewComponent.cs
using Bogus.DataSets;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Views.Shared.Components.FeaturedProperty
{
    public class FeaturedPropertyViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public FeaturedPropertyViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var featuredProperties = _context.Properties
                .Include(e => e.PropertyImages)
                .Include(e => e.Agent)
                .Include(e => e.PropertyCategory)
                .OrderBy(p => p.ConstructionDate)
                .Take(4)
                .ToList();
            return View(featuredProperties);
        }
    }
}

Views/Shared/Components/Gallery/GalleryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Views.Shared.Components.Gallery
{
    public class GalleryViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public GalleryViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var galleries = _context.PropertyImages.Take(6).ToList();

            return View(galleries);
        }
    }
}

Views/Shared/Components/Intro/IntroViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace NetCoreOakberry.Views.Shared.Components.Intro
{
    public class IntroViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Views/Shared/Components/SearchProperty/SearchPropertyViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;
using NetCoreOakberry.Models;

namespace NetCoreOakberry.Views.Shared.Components.SearchProperty
{
    public class SearchPropertyViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public SearchPropertyViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = _context.Categories
                .Where(b => b.IsActive);

            var categoriesDd = await categories
                .Select(b => new SelectListItem
                {
                    Value = b.Id.ToString(),
                    Text = b.Name
                })
                .OrderBy(b => b.Text)
                .ToListAsync();

            var vm = new SearchViewModel()
            {
                CategoriesDd = categoriesDd,
                Categories = categories.ToList(),
            };

            return View(vm);
        }
    }
}

Views/Shared/Components/SliderHero/SliderHeroViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Views.Shared.ViewComponents.SliderHeroViewComponent
{
    public class SliderHeroViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public SliderHeroViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var sliders = await _context.Sliders
            .Where(s => s.IsActive)
            .ToListAsync();

            return View(sliders);
        }
    }
}

Views/Shared/Components/Testimonial/TestimonialViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Views.Shared.Components.Testimonial
{
    public class TestimonialViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public TestimonialViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var testimonials = _context.Testimonials.Take(6).ToList();
            return View(testimonials);
        }
    }
}

Views/Shared/Components/VideoWrap/VideoWrapViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreOakberry.Persistence;

namespace NetCoreOakberry.Views.Shared.Components.VideoWrap
{
    public class VideoWrapViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public VideoWrapViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var videos = await _context.VideoWraps.FirstOrDefaultAsync();

            return View(videos);
        }
    }
}

Views/Shared/LayoutPartialViews/_FooterPartialView.cshtml
<footer class="ftco-footer">
    <div class="container-xl">
        <div class="row mb-5 pb-5 justify-content-between">
            <div class="col-md-6 col-lg">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2 logo d-flex">
                        <a class="navbar-brand align-items-center" asp-controller="Home"asp-action="Index">
                            <span class="">Ahrar <small>Gayrimenkul</small></span>
                        </a>
                    </h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                    <ul class="ftco-footer-social list-unstyled mt-2">
                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                        <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                        <li><a href="#"><span class="fa fa-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg-2">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Offers</h2>
                    <ul class="list-unstyled">
                        <li><a asp-controller="Properties"asp-action="Index"><span class="fa fa-chevron-right mr-2"></span>Properties</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Agents</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Locations</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Clients Support</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg-2">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Şirketimiz</h2>
                    <ul class="list-unstyled">
                        <li><a asp-controller="Home" asp-action="Index"><span class="fa fa-chevron-right mr-2"></span>AnaSayfa</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Hakkımızda</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Blog</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>İletişime Geçin</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg-2">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Quick Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Terms &amp; Conditions</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>User's Guide</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Support Center</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Press Info</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Sorunuz mu var?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon fa fa-map marker"></span><span class="text">Sürsürü Mahallesi, Elazığ , Merkez</span></li>
                            <li><a href="#"><span class="icon fa fa-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon fa fa-paper-plane pr-4"></span><span class="text"><span class="__cf_email__" data-cfemail="5930373f361920362c2b3d3634383037773a3634">[email&#160;protected]</span></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid px-0 py-5 bg-darken">
        <div class="container-xl">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p class="mb-0" style="color: rgba(255,255,255,.5); font-size: 13px;">Copyright &copy;<script data-cfasync="false" src="~/oakberry-main/preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank" rel="nofollow noopener">Colorlib</a>
                </div>
            </div>
        </div>
    </div>
</footer>

Views/Shared/LayoutPartialViews/_HeadPartialView.cshtml
<head>
    <title>Oakberry - Free Bootstrap 5 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/oakberry-main/prewiev/theme/oakberry/css/styles.css">
    <link rel="stylesheet" href="~/oakberry-main/prewiev/theme/oakberry/css/ionicons.min.css">
    <link rel="stylesheet" href="~/oakberry-main/prewiev/theme/oakberry/css/font-awesome.min.css" />


</head>

Views/Shared/LayoutPartialViews/_NavbarPartialView.cshtml
<nav class="navbar navbar-expand-lg  ftco-navbar-light">
    <div class="container-xl">
        <a class="navbar-brand align-items-center" asp-controller="Home" asp-action="Index">
            <span class="">Ahrar <small>Gayrimenkul</small></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav m-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="AboutUs" asp-action="Index">Hakkımızda</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Property" asp-action="Index">Portfölyo</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Agents" asp-action="Index" >Çalışanlar</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Blog" asp-action="Index">Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="contact.html">İletişim</a></li>
            </ul>
            <p class="mb-0"><a href="#" class="btn btn-primary rounded">Portfölyo Ekle</a></p>
        </div>
    </div>
</nav>

Views/Shared/LayoutPartialViews/_ScriptPartialView.cshtml
<script src="~/oakberry-main/prewiev/theme/oakberry/js/bootstrap.bundle.min.js"></script>
<script src="~/oakberry-main/prewiev/theme/oakberry/js/glitchbox.js"></script>
<script src="~/oakberry-main/prewiev/theme/oakberry/js/tiny-slider.js"></script>
<script>eval(mod_pagespeed_rdWE5e7ZHS);</script>
<script>eval(mod_pagespeed_TbXghfTMVh);</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script>eval(mod_pagespeed_Jq3FPUXGcI);</script>
<script>eval(mod_pagespeed_F7TkqtYUhP);</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag() { dataLayer.push(arguments); }
	gtag('js', new Date());

	gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"762ef5115d348ec2","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.10.3","si":100}' crossorigin="anonymous"></script>
<script nonce="ee5dee11-6e2f-4adf-a428-c5042b8369f7">
    (function (w, d) {
        !function (Z, _, ba, bb) {
            Z.zarazData = Z.zarazData || {};
            Z.zarazData.executed = [];
            Z.zaraz = { deferred: [], listeners: [] };
            Z.zaraz.q = [];
            Z.zaraz._f = function (bc) {
                return function () {
                    var bd = Array.prototype.slice.call(arguments);
                    Z.zaraz.q.push({ m: bc, a: bd });
                };
            };

            for (const be of ["track", "set", "debug"])
                Z.zaraz[be] = Z.zaraz._f(be);

            Z.zaraz.init = () => {
                var bf = _.getElementsByTagName(bb)[0],
                    bg = _.createElement(bb),
                    bh = _.getElementsByTagName("title")[0];

                bh && (Z.zarazData.t = _.getElementsByTagName("title")[0].text);
                Z.zarazData.x = Math.random();
                Z.zarazData.w = Z.screen.width;
                Z.zarazData.h = Z.screen.height;
                Z.zarazData.j = Z.innerHeight;
                Z.zarazData.e = Z.innerWidth;
                Z.zarazData.l = Z.location.href;
                Z.zarazData.r = _.referrer;
                Z.zarazData.k = Z.screen.colorDepth;
                Z.zarazData.n = _.characterSet;
                Z.zarazData.o = new Date().getTimezoneOffset();
                Z.zarazData.q = [];

                for (; Z.zaraz.q.length;) {
                    const bl = Z.zaraz.q.shift();
                    Z.zarazData.q.push(bl);
                }

                bg.defer = true;

                for (const bm of [localStorage, sessionStorage])
                    Object.keys(bm || {}).filter((bo) => bo.startsWith("_zaraz_")).forEach((bn) => {
                        try {
                            Z.zarazData["z_" + bn.slice(7)] = JSON.parse(bm.getItem(bn));
                        } catch {
                            Z.zarazData["z_" + bn.slice(7)] = bm.getItem(bn);
                        }
                    });

                bg.referrerPolicy = "origin";
                bg.src = "/oakberry-main/preview.colorlib.com/cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(Z.zarazData)));
                bf.parentNode.insertBefore(bg, bf);
            };

            ["complete", "interactive"].includes(_.readyState) ? Z.zaraz.init() : Z.addEventListener("DOMContentLoaded", Z.zaraz.init);
        }(w, d, 0, "script");
    })(window, document);
</script>

Views/Shared/LayoutPartialViews/_TopWrapPartialView.cshtml
<div class="py-4 top-wrap">
    <div class="container-xl">
        <div class="row d-flex align-items-start">
            <div class="col-md topper d-flex mb-md-0 align-items-xl-center">
                <div class="icon d-flex justify-content-center align-items-center">
                    <span class="fa fa-map"></span>
                </div>
                <div class="text pl-3 pl-md-3">
                    <p class="con"><span>Bizi Ara</span> <span>+90 532 650 3096</span></p>
                    <p class="con">Bizi 7/24 Arayabilirsiniz</p>
                </div>
            </div>
            <div class="col-md topper d-flex mb-md-0 align-items-xl-center">
                <div class="icon d-flex justify-content-center align-items-center">
                    <span class="fa fa-paper-plane"></span>
                </div>
                <div class="text pl-3 pl-md-3">
                    <p class="hr"><span>Konumumuz</span></p>
                    <p class="con">Sürsürü Mahallesi</p>
                </div>
            </div>
            <div class="col-md topper d-flex mb-md-0 align-items-xl-center">
                <div class="icon d-flex justify-content-center align-items-center">
                    <span class="fa fa-connectdevelop"></span>
                </div>
                <div class="text pl-3 pl-md-3">
                    <p class="con"><span>Bizimle </span> <span>iletişime geçin</span></p>
                    <p class="con"><a href="#">Facebook</a> <a href="#">Twitter</a> <a href="#">Dribbble</a></p>
                </div>
            </div>
        </div>
    </div>
</div>